"""empty message

Revision ID: 9521e4bb16af
Revises: 
Create Date: 2021-06-17 09:05:02.519254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9521e4bb16af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cuentas', ['password'])
    op.create_unique_constraint(None, 'cuentas', ['email'])
    op.create_unique_constraint(None, 'cuentas', ['username'])
    op.create_unique_constraint(None, 'productos', ['Codigo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='unique')
    op.drop_constraint(None, 'cuentas', type_='unique')
    op.drop_constraint(None, 'cuentas', type_='unique')
    op.drop_constraint(None, 'cuentas', type_='unique')
    # ### end Alembic commands ###
